### ISSUE TITLE
Error while build demo with tact-template

### ISSUE THREAD

**Issue by Phong2421999** [ton-community/tact#20]
I have this error while build from tact-template. Please help
`Fift decompiler crashed, skipping...
Error: Invalid argument
    at Builder.storeRef (/Users/phongphong/Desktop/atom/TON/tact-template/node_modules/ton-core/dist/boc/Builder.js:229:19)
    at fetchSubslice (/Users/phongphong/Desktop/atom/TON/tact-template/node_modules/tvm-disassembler/dist/codepages/cp0.generated.js:14:17)
    at /Users/phongphong/Desktop/atom/TON/tact-template/node_modules/tvm-disassembler/dist/codepages/cp0.generated.js:1241:24
    at decompile (/Users/phongphong/Desktop/atom/TON/tact-template/node_modules/tvm-disassembler/dist/disassembler.js:52:25)
    at fromCode (/Users/phongphong/Desktop/atom/TON/tact-template/node_modules/tvm-disassembler/dist/disassembler.js:112:15)
    at Object.compileProjects (/Users/phongphong/Desktop/atom/TON/tact-template/node_modules/ton-tact/dist/main.js:209:62)
    at async /Users/phongphong/Desktop/atom/TON/tact-template/node_modules/ton-tact/bin/tact:18:9
   > SampleTactContract: bindings`

**Comment by ex3ndr** [comment]
Is this clean checkout?

**Comment by Phong2421999** [comment]
> Is this clean checkout?

i just clone from this repo https://github.com/ton-community/tact-template and do not edit anything.

**Comment by Phong2421999** [comment]
i run `npm install` command and then when i run `npm run build` command it throw error

**Comment by ex3ndr** [comment]
Fixed, pull the changes
